import type { BuildDialogsSectionParams, BuildHeaderSectionParams, BuildItemSectionParams, BuildNowPlayingSectionParams, BuildVideoAreaSectionParams } from './playlistWindowSection.types';

export const buildPlaylistHeaderSection = ({
  playlistName,
  hasUnsavedChanges,
  exportInProgress,
  hasDualSources,
  anchorEl,
  onMenuOpen,
  onMenuClose,
  onSaveClick,
  onLoadClick,
  onViewModeChange,
  setSaveDialogOpen,
  setExportDialogOpen,
}: BuildHeaderSectionParams) => {
  return {
    playlistName,
    hasUnsavedChanges,
    exportDisabled: exportInProgress,
    hasDualSources,
    anchorEl,
    onMenuOpen,
    onMenuClose,
    onSaveClick,
    onSaveAsClick: () => setSaveDialogOpen(true),
    onLoadClick,
    onExportClick: () => setExportDialogOpen(true),
    onViewModeChange,
  };
};

export const buildPlaylistVideoAreaSection = ({
  currentVideoSource,
  currentVideoSource2,
  viewMode,
  isDrawingMode,
  drawingTarget,
  onDrawingTargetChange,
  annotationCanvasRefPrimary,
  annotationCanvasRefSecondary,
  primaryCanvasSize,
  secondaryCanvasSize,
  primaryContentRect,
  secondaryContentRect,
  currentAnnotation,
  defaultFreezeDuration,
  onObjectsChange,
  onFreezeDurationChange,
  currentTime,
  videoRef,
  videoRef2,
  hasItems,
  controlsVisible,
  sliderMin,
  sliderMax,
  marks,
  isPlaying,
  isFrozen,
  autoAdvance,
  loopPlaylist,
  isMuted,
  volume,
  isFullscreen,
  onSeek,
  onSeekCommitted,
  onPrevious,
  onTogglePlay,
  onNext,
  onToggleAutoAdvance,
  onToggleLoop,
  onToggleDrawingMode,
  onToggleMute,
  onVolumeChange,
  onToggleFullscreen,
  onVideoAreaHoverChange,
  onVideoAreaInteraction,
}: BuildVideoAreaSectionParams) => {
  return {
    currentVideoSource,
    currentVideoSource2,
    viewMode,
    isDrawingMode,
    drawingTarget,
    onDrawingTargetChange,
    annotationCanvasRefPrimary,
    annotationCanvasRefSecondary,
    primaryCanvasSize,
    secondaryCanvasSize,
    primaryContentRect,
    secondaryContentRect,
    currentAnnotation,
    defaultFreezeDuration,
    onObjectsChange,
    onFreezeDurationChange,
    currentTime,
    videoRef,
    videoRef2,
    hasItems,
    controlsVisible,
    sliderMin,
    sliderMax,
    marks,
    isPlaying,
    isFrozen,
    autoAdvance,
    loopPlaylist,
    isMuted,
    volume,
    isFullscreen,
    onSeek,
    onSeekCommitted,
    onPrevious,
    onTogglePlay,
    onNext,
    onToggleAutoAdvance,
    onToggleLoop,
    onToggleDrawingMode,
    onToggleMute,
    onVolumeChange,
    onToggleFullscreen,
    onVideoAreaHoverChange,
    onVideoAreaInteraction,
    showControls: hasItems,
  };
};

export const buildPlaylistItemSection = ({
  items,
  currentIndex,
  selectedItemIds,
  sensors,
  onDragEnd,
  onRemove,
  onPlay,
  onEditNote,
  onToggleSelect,
}: BuildItemSectionParams) => {
  return {
    items,
    currentIndex,
    selectedItemIds,
    sensors,
    onDragEnd,
    onRemove,
    onPlay,
    onEditNote,
    onToggleSelect,
  };
};

export const buildPlaylistNowPlayingSection = (params: BuildNowPlayingSectionParams) => {
  if (!params.currentItem) {
    return null;
  }

  return {
    currentItem: params.currentItem,
    isFrozen: params.isFrozen,
    currentIndex: params.currentIndex,
    totalCount: params.totalCount,
    annotation: params.currentAnnotation ?? undefined,
  };
};

export const buildPlaylistDialogsSection = ({
  saveDialogOpen,
  onCloseSaveDialog,
  onSavePlaylistAs,
  playlistName,
  playlistType,
  closeAfterSave,
  exportDialogOpen,
  onCloseExportDialog,
  onExportPlaylist,
  exportFileName,
  setExportFileName,
  exportScope,
  setExportScope,
  selectedCount,
  exportMode,
  setExportMode,
  angleOption,
  setAngleOption,
  videoSources,
  selectedAngleIndex,
  setSelectedAngleIndex,
  overlaySettings,
  setOverlaySettings,
  exportInProgress,
  noteDialogOpen,
  onCloseNoteDialog,
  onSaveNote,
  initialNote,
  itemName,
  saveProgress,
  exportProgress,
  onCloseExportProgress,
}: BuildDialogsSectionParams) => {
  return {
    saveDialog: {
      open: saveDialogOpen,
      onClose: onCloseSaveDialog,
      onSave: onSavePlaylistAs,
      defaultName: playlistName,
      defaultType: playlistType,
      closeAfterSave,
    },
    exportDialog: {
      open: exportDialogOpen,
      onClose: onCloseExportDialog,
      onExport: onExportPlaylist,
      exportFileName,
      setExportFileName,
      exportScope,
      setExportScope,
      selectedItemCount: selectedCount,
      exportMode,
      setExportMode,
      angleOption,
      setAngleOption,
      videoSources,
      selectedAngleIndex,
      setSelectedAngleIndex,
      overlaySettings,
      setOverlaySettings,
      disableExport: exportInProgress,
    },
    noteDialog: {
      open: noteDialogOpen,
      onClose: onCloseNoteDialog,
      onSave: onSaveNote,
      initialNote,
      itemName,
    },
    progress: {
      saveProgress,
      exportProgress,
      onCloseExportProgress,
    },
  };
};
