import type { HotkeyConfig } from '../../../types/Settings';

export const DEFAULT_HOTKEYS: HotkeyConfig[] = [
  { id: 'resync-audio', label: '音声同期を再実行', key: 'Command+Shift+S' },
  { id: 'reset-sync', label: '同期をリセット', key: 'Command+Shift+R' },
  { id: 'manual-sync', label: '今の位置で同期', key: 'Command+Shift+M' },
  { id: 'toggle-manual-mode', label: '手動モード切替', key: 'Command+Shift+T' },
  { id: 'analyze', label: '分析開始', key: 'Command+Shift+A' },
  { id: 'undo', label: '元に戻す', key: 'Command+Z' },
  { id: 'redo', label: 'やり直す', key: 'Command+Shift+Z' },
  { id: 'skip-forward-small', label: '0.5秒進む', key: 'Right' },
  { id: 'skip-forward-medium', label: '2秒進む', key: 'Shift+Right' },
  { id: 'skip-forward-large', label: '4秒進む', key: 'Command+Right' },
  { id: 'skip-forward-xlarge', label: '6秒進む', key: 'Option+Right' },
  { id: 'skip-backward-medium', label: '5秒戻る', key: 'Left' },
  { id: 'skip-backward-large', label: '10秒戻る', key: 'Shift+Left' },
  { id: 'play-pause', label: '再生/一時停止', key: 'Space' },
  { id: 'toggle-angle1', label: 'アングル1切替', key: 'Shift+1' },
  { id: 'toggle-angle2', label: 'アングル2切替', key: 'Shift+2' },
];

export const FORBIDDEN_HOTKEYS = new Set([
  'Command+Q',
  'Command+W',
  'Command+N',
  'Command+T',
  'Command+C',
  'Command+V',
  'Command+X',
  'Command+A',
  'Command+S',
  'Command+O',
  'Command+P',
  'Command+F',
  'Command+H',
  'Command+M',
  'Command+Tab',
  'Command+Space',
  'Control+Space',
]);
