import type { useAIAnalysisTabState } from './useAIAnalysisTabState';

type AIAnalysisTabState = ReturnType<typeof useAIAnalysisTabState>;

export const pickAIAnalysisPublicState = (state: AIAnalysisTabState) => {
  return {
    aiSettings: state.aiSettings,
    setAiSettings: state.setAiSettings,
    question: state.question,
    setQuestion: state.setQuestion,
    startTime: state.startTime,
    setStartTime: state.setStartTime,
    endTime: state.endTime,
    setEndTime: state.setEndTime,
    labelGroup: state.labelGroup,
    setLabelGroup: state.setLabelGroup,
    labelName: state.labelName,
    setLabelName: state.setLabelName,
    teamName: state.teamName,
    setTeamName: state.setTeamName,
    showAiSettings: state.showAiSettings,
    setShowAiSettings: state.setShowAiSettings,
    showFilters: state.showFilters,
    setShowFilters: state.setShowFilters,
    showAllEvidence: state.showAllEvidence,
    setShowAllEvidence: state.setShowAllEvidence,
    isEvidenceAccordionOpen: state.isEvidenceAccordionOpen,
    setIsEvidenceAccordionOpen: state.setIsEvidenceAccordionOpen,
    isInsightAccordionOpen: state.isInsightAccordionOpen,
    setIsInsightAccordionOpen: state.setIsInsightAccordionOpen,
    isSettingsAccordionOpen: state.isSettingsAccordionOpen,
    setIsSettingsAccordionOpen: state.setIsSettingsAccordionOpen,
    insightDimension: state.insightDimension,
    setInsightDimension: state.setInsightDimension,
    retrievalStatus: state.retrievalStatus,
    generationStatus: state.generationStatus,
    retrievalError: state.retrievalError,
    generationError: state.generationError,
    evidenceItems: state.evidenceItems,
    aiResponse: state.aiResponse,
    llmRawText: state.llmRawText,
    llmLiveLog: state.llmLiveLog,
    llmAttempt: state.llmAttempt,
    llmRetryInfo: state.llmRetryInfo,
    llmDebug: state.llmDebug,
    llmWarning: state.llmWarning,
    showDebug: state.showDebug,
    setShowDebug: state.setShowDebug,
    settingsMessage: state.settingsMessage,
    playlistMessage: state.playlistMessage,
    generationRequestId: state.generationRequestId,
    llmProgress: state.llmProgress,
  };
};
